bookmark/urls.py
from django.urls import path
from .views import BookmarkListView, BookmarkCreateView, BookmarkDetailView, BookmarkUpdateView, BookmarkDeleteView

app_name = 'bookmark'

urlpatterns = [
    path('', BookmarkListView.as_view(), name = 'list'),
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('detail/<int:pk>/', BookmarkDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BookmarkDeleteView.as_view(), name='delete'),
]

cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('', views.CalendarView.as_view(), name='calender'),
    path('new', views.event, name='event_new'),
    path('edit', views.event, name='event_edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings

urlpatterns = [
    path('hackernews/', include('hackernews.urls')),
    path('todo/', include('bulma_todo.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    # path('profile/', user_views.profile, name='profile'),
    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('tools/', include('tools.urls')),
    path('lotto/', include('mylotto.urls')),
    # path('users/', include('users.urls')),
    path('polls/', include('polls.urls')),
    path('cal/', include('cal.urls')),
    path('boards/', include('boards.urls')),
    path('schedule/', include('schedule.urls')),
    # path('events/', include('events.urls')),
    path('crud/', include('crud.urls')),
    path('news/', include('news.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('wordcount/', include('wordcount.urls')),
    path('csv/', include('csv_app.urls')),
    path('catalog/', include('catalog.urls')),
    path('', include('blog.urls')),
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

bookmark/models.py
from django.db import models


class Bookmark(models.Model):
    site_name = models.CharField(max_length=100)
    url = models.URLField('site URL')

    def __str__(self):
        return self.site_name

bookmark/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from .models import Bookmark
from django.urls import reverse_lazy # 타이밍 로딩 문제로 generic view에서는 reverse는 사용할 수 없고 reverse_lazy를 사용해야한다.

class BookmarkListView(ListView):
    model = Bookmark
    # paginate_by = 5 # 페이지 만들기, 지금은 별로 필요없어서 안함
    # template_name = 'bookmark_list.html'
    # context_object_name = 'bookmark_list'
    # def get_queryset(self):
    #     return Bookmark.objects.all()

class BookmarkCreateView(CreateView):
    model = Bookmark
    fields = ['site_name', 'url']
    success_url = reverse_lazy('bookmark:list')
    template_name_suffix = '_create'

class BookmarkDetailView(DetailView):
    model = Bookmark

class BookmarkUpdateView(UpdateView):
    model = Bookmark
    fields = ['site_name','url']
    template_name_suffix = '_update'
    success_url = reverse_lazy('bookmark:list')

class BookmarkDeleteView(DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:list')

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>
 Bookmark app
</h1>
<div>
    <form action="" method="post">
        {% csrf_token %}
        <div class="alert alert-danger">
            {{ object }} 를 진짜로 삭제하시겠습니까?
        </div>
        <input type="submit" value="Delete" class="btn btn-info btn-sm">
    </form>

</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}

{% block content %}
<h1>
 Bookmark app
</h1>
<div>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" class="btn btn-info btn-sm">
</form>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>
 Bookmark app
</h1>
<div>
 {{ object.site_name }} <br/>
 {{ object.url }}
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block content %}
<h1>
 Bookmark app
</h1>
<div>
    <div class='btn-group'>
        <a href="{% url 'bookmark:add' %}" class="btn btn-info">
            Add Bookmark
        </a>
    </div>
    <p>

    </p>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Site</th>
                <th scope="col">URL</th>
                <th scope="col">Modify</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for bookmark in object_list %}
            <tr>
                <td>
                    {{forloop.counter}}
                </td>
                <td><a href="{% url 'bookmark:detail' pk=bookmark.id %}">{{ bookmark.site_name }}</a></td>
                <td><a href="{{ bookmark.url }}">{{ bookmark.url }}</a></td>
                <td><a href="{% url 'bookmark:update' pk=bookmark.id %}" class="btn btn-success btn-sm">Modify</a></td>
                <td><a href="{% url 'bookmark:delete' pk=bookmark.id %}" class="btn btn-danger btn-sm">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}

{% block content %}
<h1>
 Bookmark app
</h1>
<div>
 <form action="" method="post">
     {% csrf_token %}
     {{ form.as_p }}
     <input type="submit" value="Update" class="btn btn-info btn-sm">
 </form>
</div>
{% endblock %}