cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('', views.CalendarView.as_view(), name='calender'),
    path('new', views.event, name='event_new'),
    path('edit', views.event, name='event_edit'),
]

hackernews/urls.py
from django.urls import path, include
from .views import frontpage, search, submit, newest, vote, story

app_name="hackernews"

urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('<int:story_id>/vote/', vote, name='vote'),
    path('<int:story_id>/', story, name='story'),
    # path('u/', include('apps.userprofile.urls')),
    path('newest/', newest, name='newest'),
    path('search/', search, name='search'),
    path('submit/', submit, name='submit'),
]

## user profile

from .views import userprofile, votes, submissions

urlpatterns += [
    path('<str:username>/', userprofile, name='userprofile'),
    path('<str:username>/votes/', votes, name='votes'),
    path('<str:username>/submissions/', submissions, name='submissions'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings

urlpatterns = [
    path('hackernews/', include('hackernews.urls')),
    path('todo/', include('bulma_todo.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    # path('profile/', user_views.profile, name='profile'),
    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('tools/', include('tools.urls')),
    path('lotto/', include('mylotto.urls')),
    # path('users/', include('users.urls')),
    path('polls/', include('polls.urls')),
    path('cal/', include('cal.urls')),
    path('boards/', include('boards.urls')),
    path('schedule/', include('schedule.urls')),
    # path('events/', include('events.urls')),
    path('crud/', include('crud.urls')),
    path('news/', include('news.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('wordcount/', include('wordcount.urls')),
    path('csv/', include('csv_app.urls')),
    path('catalog/', include('catalog.urls')),
    path('', include('blog.urls')),
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

hackernews/models.py
from django.db import models
from django.contrib.auth.models import User

class Story(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()

    number_of_votes = models.IntegerField(default=1)

    created_by = models.ForeignKey(User, related_name='stories', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return '%s' % self.title

class Vote(models.Model):
    story = models.ForeignKey(Story, related_name='votes', on_delete=models.CASCADE)

    created_by = models.ForeignKey(User, related_name='votes', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.story.number_of_votes = self.story.number_of_votes + 1
        self.story.save()

        super(Vote, self).save(*args, **kwargs)

class Comment(models.Model):
    story = models.ForeignKey(Story, related_name='comments', on_delete=models.CASCADE)

    body = models.TextField()

    created_by = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

hackernews/forms.py
from django import forms

from .models import Story, Comment

class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = ('title', 'url')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

hackernews/views.py
import datetime
from django.utils import timezone

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import StoryForm, CommentForm
from .models import Story, Vote, Comment

def frontpage(request):
    date_from = timezone.now() - datetime.timedelta(days=1)

    stories = Story.objects.filter(created_at__gte=date_from).order_by('-number_of_votes')[0:30]

    return render(request, 'hackernews/frontpage.html', {'stories': stories})

def search(request):
    query = request.GET.get('query', '')

    if len(query) > 0:
        stories = Story.objects.filter(title__icontains=query)
    else:
        stories = []
    
    return render(request, 'hackernews/search.html', {'stories': stories, 'query': query})

def story(request, story_id):
    story = get_object_or_404(Story, pk=story_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.story = story
            comment.created_by = request.user
            comment.save()

            return redirect('hackernews:story', story_id=story_id)
    else:
        form = CommentForm()
    
    return render(request, 'hackernews/detail.html', {'story': story, 'form': form})

def newest(request):
    stories = Story.objects.all()[0:200]

    return render(request, 'hackernews/newest.html', {'stories': stories})

@login_required
def vote(request, story_id):
    story = get_object_or_404(Story, pk=story_id)

    next_page = request.GET.get('next_page', '')

    if story.created_by != request.user and not Vote.objects.filter(created_by=request.user, story=story):
        vote = Vote.objects.create(story=story, created_by=request.user)
    
    if next_page == 'story':
        return redirect('hackernews:story', story_id=story_id)
    else:
        return redirect('hackernews:frontpage')

@login_required
def submit(request):
    if request.method == 'POST':
        form = StoryForm(request.POST)

        if form.is_valid():
            story = form.save(commit=False)
            story.created_by = request.user
            story.save()

            return redirect('hackernews:frontpage')
    else:
        form = StoryForm()

    return render(request, 'hackernews/submit.html', {'form': form})




## user profile

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User

def userprofile(request, username):
    user = get_object_or_404(User, username=username)

    number_of_votes = 0

    for story in user.stories.all():
        number_of_votes = number_of_votes + (story.number_of_votes - 1)
    
    return render(request, 'hackernews/userprofile.html', {'user': user, 'number_of_votes': number_of_votes})

def votes(request, username):
    user = get_object_or_404(User, username=username)
    votes = user.votes.all()

    stories = []

    for vote in votes:
        stories.append(vote.story)
    
    return render(request, 'hackernews/votes.html', {'user': user, 'stories': stories})

def submissions(request, username):
    user = get_object_or_404(User, username=username)

    stories = user.stories.all()

    return render(request, 'hackernews/submissions.html', {'user': user, 'stories': stories})

hackernews/templates/hackernews/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="columns">
            <div class="column is-12">
                <h1 class="title">{{ story.title }}</h1>
                <h2 class="subtitle">{{ story.number_of_votes }} votes</h2>
            
                <strong>By: </strong><a href="{% url 'hackernews:userprofile' story.created_by.username %}">{{ story.created_by.username }}</a> {{ story.created_at|timesince }} ago<br>
                <strong>Visit: </strong><a href="{{ story.url }}" target="_blank">{{ story.url }}</a>
            
                <hr>

                {% if not story.created_by == request.user %}<a href="{% url 'hackernews:vote' story.id %}?next_page=story" class="button is-success">Vote</a>{% endif %}
            </div>
        </div>

        <div class="columns">
            <div class="column is-12">
                <hr>

                <h2 class="subtitle">Comments</h2>

                {% for comment in story.comments.all %}
                    <article class="media">
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <strong>{{ comment.created_by.username }}</strong> <small>{{ comment.created_at|timesince }} ago</small><br>
                                    {{ comment.body }}
                                </p>
                            </div>
                        </div>
                    </article>
                {% empty %}
                    <p>No comments yet!</p>
                {% endfor %}

                <hr>

                <h2 class="subtitle">Add comment</h2>

                {% if request.user.is_authenticated %}
                    <form method="post" action=".">
                        {% csrf_token %}

                        {{ form.as_p }}

                        <div class="field">
                            <div class="field">
                                <button class="button is-success">Submit</button>
                            </div>
                        </div>
                    </form>
                {% else %}
                    <p>Please log in to comment!</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

hackernews/templates/hackernews/frontpage.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="columns">
    <div class="column is-12">
      <h1 class="title">This is hacker news clone!</h1>
      <a href={% url 'hackernews:submit' %}> Add new entry</a>
    </div>
  </div>
    <form method="get" action="{% url 'hackernews:search' %}">
  <div class="field has-addons">
    <div class="control mb-3">
      <input type="text" class="input" placeholder="Search..." name="query" />
      <button class="button is-success">Search</button>
    </div>
  </div>
</form>


  <div class="columns">
    <div class="column is-12">
      <table class="table is-striped is-fullwidth">
        <tbody>
          {% for story in stories %}
          <tr>
            <td>{{ forloop.counter }}.</td>
            <td>
              <a href="{{ story.url }}" target="_blank">{{ story.title }}</a>
              <p>
                {{ story.number_of_votes }} votes by {{ story.created_by.username }} {{ story.created_at|timesince }}
                ago | {% if not story.created_by == request.user %}<a
                  href="{% url 'hackernews:vote' story.id %}"
                  >Vote</a
                >{% endif %}
                <a href="{% url 'hackernews:story' story.id %}">Discuss</a>
              </p>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>


{% endblock %}

hackernews/templates/hackernews/newest.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="columns">
    <div class="column is-12">
      <h1 class="title">Newest</h1>
    </div>
  </div>

  <div class="columns">
    <div class="column is-12">
      <table class="table is-striped is-fullwidth">
        <tbody>
          {% for story in stories %}
          <tr>
            <td>{{ forloop.counter }}.</td>
            <td>
              <a href="{{ story.url }}" target="_blank">{{ story.title }}</a>
              <p>
                {{ story.number_of_votes }} votes by {{
                story.created_by.username }} {{ story.created_at|timesince }}
                ago | {% if not story.created_by == request.user %}<a
                  href="{% url 'hackernews:vote' story.id %}"
                  >Vote</a
                >{% endif %}
                <a href="{% url 'hackernews:story' story.id %}">Discuss</a>
              </p>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

hackernews/templates/hackernews/search.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="columns">
            <div class="column is-12">
                <h1 class="title">Search</h1>
                <h2 class="subtitle">Query: "{{ query }}"</h2>
            </div>
        </div>

        <div class="columns">
    <div class="column is-12">
        <table class="table is-striped is-fullwidth">
            <tbody>
                {% for story in stories %}
                    <tr>
                        <td>{{ forloop.counter }}.</td>
                        <td>
                            <a href="{{ story.url }}" target="_blank">{{ story.title }}</a>
                            <p>
                                {{ story.number_of_votes }} votes by {{ story.created_by.username }} {{ story.created_at|timesince }} ago | 
                                
                                {% if not story.created_by == request.user %}<a href="{% url 'hackernews:vote' story.id %}">Vote</a>{% endif %}
                                <a href="{% url 'hackernews:story' story.id %}">Discuss</a>
                            </p>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
    </div>
{% endblock %}

hackernews/templates/hackernews/submissions.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="columns">
            <div class="column is-12">
                <h1 class="title">Submissions</h1>
            </div>
        </div>

        <div class="columns">
    <div class="column is-12">
      <table class="table is-striped is-fullwidth">
        <tbody>
          {% for story in stories %}
          <tr>
            <td>{{ forloop.counter }}.</td>
            <td>
              <a href="{{ story.url }}" target="_blank">{{ story.title }}</a>
              <p>
                {{ story.number_of_votes }} votes by {{
                story.created_by.username }} {{ story.created_at|timesince }}
                ago | {% if not story.created_by == request.user %}<a
                  href="{% url 'hackernews:vote' story.id %}"
                  >Vote</a
                >{% endif %}
                <a href="{% url 'hackernews:story' story.id %}">Discuss</a>
              </p>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
    </div>
{% endblock %}

hackernews/templates/hackernews/submit.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="columns">
            <div class="column is-12">
                <h1 class="title">New story</h1>
            </div>
        </div>

        <div class="columns">
            <div class="column is-12">
                <form method="post" action=".">
                    {% csrf_token %}

                    {{ form.as_p }}

                    <div class="field">
                        <div class="control">
                            <button class="button is-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

hackernews/templates/hackernews/userprofile.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="columns">
            <div class="column is-12">
                <h1 class="title">{{ user.username }}</h1>
                <h2 class="subtitle">{{ number_of_votes }} votes</h2>
            
                <hr>

                <a href="{% url 'hackernews:submissions' user.username %}">Submissions</a> | 
                <a href="{% url 'hackernews:votes' user.username %}">Votes</a>
            </div>
        </div>
    </div>
{% endblock %}

hackernews/templates/hackernews/vote.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="columns">
            <div class="column is-12">
                <h1 class="title">Voted stories</h1>
            </div>
        </div>

        <div class="columns">
    <div class="column is-12">
        <table class="table is-striped is-fullwidth">
            <tbody>
                {% for story in stories %}
                    <tr>
                        <td>{{ forloop.counter }}.</td>
                        <td>
                            <a href="{{ story.url }}" target="_blank">{{ story.title }}</a>
                            <p>
                                {{ story.number_of_votes }} votes by {{ story.created_by.username }} {{ story.created_at|timesince }} ago | 
                                
                                {% if not story.created_by == request.user %}<a href="{% url 'hackernews:vote' story.id %}">Vote</a>{% endif %}
                                <a href="{% url 'hackernews:story' story.id %}">Discuss</a>
                            </p>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
    </div>
{% endblock %}