cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('', views.CalendarView.as_view(), name='calender'),
    path('new', views.event, name='event_new'),
    path('edit', views.event, name='event_edit'),
]

crud/urls.py
from django.urls import path
from . import views

app_name = 'crud'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('post/', views.postview, name='post'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings

urlpatterns = [
    path('hackernews/', include('hackernews.urls')),
    path('todo/', include('bulma_todo.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    # path('profile/', user_views.profile, name='profile'),
    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('tools/', include('tools.urls')),
    path('lotto/', include('mylotto.urls')),
    # path('users/', include('users.urls')),
    path('polls/', include('polls.urls')),
    path('cal/', include('cal.urls')),
    path('boards/', include('boards.urls')),
    path('schedule/', include('schedule.urls')),
    # path('events/', include('events.urls')),
    path('crud/', include('crud.urls')),
    path('news/', include('news.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('wordcount/', include('wordcount.urls')),
    path('csv/', include('csv_app.urls')),
    path('catalog/', include('catalog.urls')),
    path('', include('blog.urls')),
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

crud/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=120, help_text='메세지의 제목')
    message = models.TextField(help_text='니 생각은 어때?')

    def __str__(self):
        return self.title

crud/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"

crud/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm
from .models import Post
from django.views.generic import ListView, DetailView
from django.http import HttpResponse

# def index(request):
#  got   return HttpResponse('hello world!')

#home view for posts. Posts are displayed in a list
class IndexView(ListView):
    template_name='crud/index.html'
    context_object_name = 'post_list'
    def get_queryset(self):
        return Post.objects.all()

#Detail view (view post detail)
class PostDetailView(DetailView):
    model=Post
    template_name = 'crud/post-detail.html'

#New post view (Create new post)
def postview(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('crud:index')
    form = PostForm()
    return render(request,'crud/post.html',{'form': form})
    
#Edit a post
def edit(request, pk, template_name='crud/edit.html'):
    post= get_object_or_404(Post, pk=pk)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('crud:index')
    return render(request, template_name, {'form':form})

#Delete post
def delete(request, pk, template_name='crud/confirm_delete.html'):
    post= get_object_or_404(Post, pk=pk)    
    if request.method=='POST':
        post.delete()
        return redirect('crud:index')
    return render(request, template_name, {'object':post})

crud/templates/crud/confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<div class="row"></div>
<br/>
<div class="row">
<div class="col-md-2 col-xs-2 col-sm-2"></div>
 <div class="col-md-10 col-xs-10 col-sm-10">
  <form method="post">
   {% csrf_token %}
    <div class="form-row">
      <div class="alert alert-warning">
       Are you sure you want to delete {{ object }}?
      </div>
    </div>
    <button type="submit" class="btn btn-danger">
     <span class="glyphicon glyphicon-trash">delete</span>
    </button>
  </form>
 </div>
</div>
</div>
{% endblock %}

crud/templates/crud/edit.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
 <div class="row">
  <div class="col-md-1 col-xs-1 col-sm-1"></div>
  <div  class="col-md-10 col-xs-10 col-sm-10 ">
  <br/>
   <h6 style="text-align:center;">
    All fields are require
  </h6>
  </div>
  <div class="col-md-1 col-xs-1 col-sm-1">
  </div>
 </div>
 <div class="row">
  <div class="col-md-1 col-xs-1 col-sm-1"></div>
  <div class="col-md-10 col-xs-10 col-sm-10">
   <form method="post" novalidate>
     {% csrf_token %}
     {% for hidden_field in form.hidden_fields %}
       {{ hidden_field }}
     {% endfor %}
     {% for field in form.visible_fields %}
       <div class="form-group">
         {{ field.label_tag }}
         {% render_field field class="form-control" %}
         {% if field.help_text %}
           <small class="form-text text-muted">{{ field.help_text }}</small>
         {% endif %}
       </div>
     {% endfor %}
     <button type="submit" class="btn btn-primary">submit</button>
   </form>
   <br>
  </div>
  <div class="col-md-1 col-xs-1 col-sm-1"></div>
 </div>
 {% endblock %}

crud/templates/crud/index.html
{% extends 'base.html' %}
{% block content %}

    <div class="row mt-1">
        <div class="col-md-10 col-xs-10 col-sm-10">
            <h3 class="round3" style="text-align:center;">CRUD app example</h3>
        </div>
        <div class="col-md-2 col-xs-1 col-sm-1">
            <a href="{% url 'crud:post' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus">Add post</span>
                </button>
            </a>
        </div>
    </div>
    <div class="row mt-3">
                {% for post in post_list %}
                        <div class="col-md-6" style="text-align: left;">
                            <a href="{% url 'crud:detail' post.pk %}">
                                {{ post.title }}
                            </a>
                        </div>
                        <div class="col-md-6" style="text-align: right;">
                            <a href="{% url 'crud:edit' post.pk %}">
                                edit
                            </a>
                            <a href="{% url 'crud:delete' post.pk %}">
                                delete
                            </a>
                        </div>
                    {% endfor %}
    </div>
{% endblock %}

crud/templates/crud/post-detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row mt-5 py-3">
 <div class="col-md-8 col-xs-8 col-sm-8">
  <p class="h2">
   {{post.title}}
  </p>
    </div>
 <div class="col-md-1 col-xs-1 col-sm-1">
  <a href="{% url 'crud:edit' post.pk %}">
   <button type="button" class="btn btn-info">
    <span class="glyphicon glyphicon-pencil">Edit</span>
   </button>
  </a>
 </div>
 <div class="col-md-1 col-xs-1 col-sm-1">
  <a href="{% url 'crud:delete' post.pk %}">
   <button type="button" class="btn btn-danger">
    <span class="glyphicon glyphicon-trash">Delete</span>
   </button>
  </a>
 </div>
</div>
<div class="row">
 <div class="col-md-1 col-xs-1 col-sm-1"></div>
 <div class="col-md-10 col-xs-10 col-sm-10">
 {{post.message}}
 </div>
 <div class="col-md-1 col-xs-1 col-sm-1"></div>
</div>
{% endblock %}

crud/templates/crud/post.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
 <div class="row">
  <div class="col-md-1 col-xs-1 col-sm-1"></div>
 
  <div  class="col-md-10 col-xs-10 col-sm-10 ">
  <br/>
   <h6 style="text-align:center;"><font color="red"> All fields are required</font> </h6>
  </div>
  <div class="col-md-1 col-xs-1 col-sm-1">
  </div>
 </div>
 <div class="row">
  <div class="col-md-1 col-xs-1 col-sm-1"></div>
  <div class="col-md-10 col-xs-10 col-sm-10">
   <form method="post" novalidate>
     {% csrf_token %}
     {% for hidden_field in form.hidden_fields %}
     {{ hidden_field }}
     {% endfor %}
     {% for field in form.visible_fields %}
       <div class="form-group">
         {{ field.label_tag }}
         {% render_field field class="form-control" %}
         {% if field.help_text %}
           <small class="form-text text-muted">{{ field.help_text }}</small>
         {% endif %}
       </div>
     {% endfor %}<button type="submit" class="btn btn-primary">post</button>
   </form>
   <br>
  </div>
  <div class="col-md-1 col-xs-1 col-sm-1"></div>
 </div>
{% endblock %}